docker-deploy/web-app/firsthomework/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('rideshare/', include('rideshare.urls')),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='rideshare/', permanent=True)),
]

# Use static() to add URL mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

docker-deploy/web-app/rideshare/urls.py
from django.urls import path, include
from . import views

app_name = "rideshare"
urlpatterns = [
    # Can use reverse URL mapping such as: <a href="{% url 'index' %}">Home</a> to make a hyperlink to the page
    path('', views.index, name='index'),
    path('signup', views.signup, name='signup'),
    path('login', views.userLogin, name='login'),

    path("driver/register", views.DriverView.driverRegister, name="driverRegister"),
    path("driver/edit", views.DriverView.driverEdit, name="driverEdit"),
    path("driver/main", views.DriverView.driverMain, name="driverMain"),
    path("driver/search", views.DriverView.driverSearch, name="driverSearch"),
    path("<uuid:ride_id>/update/<str:status>", views.DriverView.updateRideStatus, name="updateRideStatus"),

    path("sharer/main", views.SharerView.sharerMain, name = "sharerMain"),
    path("sharer/search", views.SharerView.sharerSearch, name="sharerSearch"),
    path("sharer/<uuid:ride_id>/join", views.SharerView.shareJoin, name="sharerJoin"),
    path("sharer/<uuid:ride_id>/edit", views.SharerView.shareEdit, name="sharerEdit"),
    
    path('rides', views.RideListView.as_view(), name='rides'),
    path('rides/<uuid:pk>/', views.OwnerView.ride_detail_view, name='ride-detail'),

    path("owner/rides", views.OwnerView.owner_rides_view, name="owner-rides"),
    path("owner/request", views.OwnerView.owner_request_view, name="owner-request"),
    path("owner/edit/<uuid:ride_id>/", views.OwnerView.owner_edit_view, name="owner-edit"),
    path("owner/delete/<uuid:ride_id>/", views.OwnerView.owner_delete, name="owner-delete")
]

docker-deploy/web-app/rideshare/models.py
from django.db import models
from django.contrib.auth.models import User
from enum import Enum
import uuid 


class VehicleType(Enum):
    SMALL = 'small'
    MEDIUM = 'medium'
    LARGE = 'large'

class RideStatus(Enum):
    OPEN = 'Open'
    CONFIRMED = 'Confirmed'
    COMPLETE = 'Complete'

class Sharer(models.Model):

    destination = models.CharField(max_length=255)
    earliest_arrival_time = models.DateTimeField()
    latest_arrival_time = models.DateTimeField()
    num_passengers = models.IntegerField()

    # ForeignKey field for Ride
    ride = models.ForeignKey('Ride', on_delete=models.CASCADE)

    # ForeignKey field for User
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Sharer to {self.destination}'

class Driver(models.Model):

    name = models.CharField(max_length=255)
    vehicle_type = models.CharField(
        max_length=20,
        choices=[(item.value, item.name) for item in VehicleType],
        default=VehicleType.SMALL.value
    )
    capacity = models.IntegerField()
    license_plate_number = models.CharField(max_length=20)
    special_vehicle_info = models.TextField(blank=True, null=True)
    
    user = models.ForeignKey(User, on_delete=models.CASCADE) 

    def __str__(self):
        return self.name

from datetime import datetime

class Ride(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
    destination_address = models.CharField(max_length=255)
    required_arrival_time = models.DateTimeField(default=datetime(2024, 12, 31, 23, 59, 59))
    vehicle_type = models.CharField(
        max_length=20,
        choices=[(item.value, item.name) for item in VehicleType],
        default=None  # Default to 'small' if not specified
    )

    num_passengers = models.IntegerField()
    shared = models.BooleanField()
    special_requests = models.TextField(blank=True, null=True)

    status = models.CharField(
        max_length=20,
        choices=[(item.value, item.name) for item in RideStatus],
        default=RideStatus.OPEN.value
    )
    
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rides_as_owner')
    driver = models.ForeignKey(Driver, on_delete=models.CASCADE, related_name='rides_as_driver', blank=True, null=True)

    def get_absolute_url(self):
        return reverse('ride-detail', args=[str(self.id)])

    def delete_ride(self):
        """Delete this ride instance."""
        self.delete()
        
    def __str__(self):
        return f'Ride to {self.destination_address}'

docker-deploy/web-app/rideshare/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.forms.models import model_to_dict
from django.contrib.auth import authenticate, login
from django.core.exceptions import ValidationError
from .models import User, Driver, Ride, RideStatus, Sharer
from .forms import SignupForm, DriverForm, SharerForm, OwnerEditForm, OwnerRequestForm

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, F, Value, IntegerField
from django.db.models.functions import Coalesce

import os.path
import base64

import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

import datetime
from django.utils import timezone



# Renders the HTML template with the data in the context variable
def signup(request):
    form = SignupForm()

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = SignupForm(request.POST)
        print(form.errors)

        # Check if the form is valid:
        if form.is_valid():
            print("valid")
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            user = form.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('rideshare:login') )

    # If this is a GET (or any other method) create the default form.       
    return render(request, 'signup.html', {'form': form})

def userLogin(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            
            # Redirect to a success page.
            return HttpResponseRedirect(reverse('rideshare:index') )
        else:
            messages.error(request,'username or password not correct')
            return HttpResponseRedirect(reverse(('rideshare:login')))
    return render(request, "login.html")

@login_required()
def index(request):
    """View function for home page of site."""
    user = request.user

    num_rides = Ride.objects.filter(owner_id=user.id).count()
    num_drivers = Driver.objects.filter(user=user).count()
    num_sharers = Sharer.objects.filter(user=user).count()


    context = {
        'num_rides': num_rides,
        'num_drivers': num_drivers,
        'num_sharers': num_sharers
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


def send_email(subject, to_email, html_content):
    try:
        sg = SendGridAPIClient('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')
        message = Mail(
            from_email='alejandroyiweihe@gmail.com',
            to_emails=to_email,
            subject=subject,
            html_content=html_content
        )
        response = sg.send(message)
        print(response.status_code)
        print(response.body)
        print(response.headers)
    except Exception as e:
        print(f"Error sending email: {str(e)}")


# Driver
class DriverView(LoginRequiredMixin):

    @login_required()
    def updateRideStatus(request, ride_id, status):
        ride = get_object_or_404(Ride, pk = ride_id)
        driver = get_object_or_404(Driver, user=request.user)

        ride.status = status
        ride.driver = driver

        ride.save()

        if status == RideStatus.CONFIRMED.value:
            subject = "Ride Confirmed"
            to_email = ride.owner.email
            html_content = f"""
                    <h1>Dear {ride.owner.first_name} {ride.owner.last_name},</h1>
                    <h1>Your ride to {ride.destination_address} has been confirmed.</h1>
                    <h1>Your driver is {driver.name}.</h1>
                """
            send_email(subject, to_email, html_content)
        return HttpResponseRedirect(reverse('rideshare:driverMain'))

    @login_required()
    def driverRegister(request):
        user = request.user

        # Try to get the existing Driver instance, or create a new one if it doesn't exist
        try:
            driver = Driver.objects.get(user=user)
            form = DriverForm(instance=driver)
        except Driver.DoesNotExist:
            driver = None
            form = DriverForm()
        
        # If this is a POST request then process the Form data
        if request.method == 'POST':

            # Create a form instance and populate it with data from the request (binding):
            form = DriverForm(request.POST, instance=driver)

            # Check if the form is valid:
            if form.is_valid():
                form.instance.user = user
                driver = form.save()

                # redirect to a new URL:
                return HttpResponseRedirect(reverse('rideshare:driverMain') )

        # If this is a GET (or any other method) create the default form.       
        return render(request, "rideshare/driver/register.html", {'form': form})

    @login_required()
    def driverEdit(request):
        driver = get_object_or_404(Driver, user = request.user)
        form = DriverForm(instance=driver)

        # If this is a POST request then process the Form data
        if request.method == 'POST':

            # Create a form instance and populate it with data from the request (binding):
            form = DriverForm(request.POST, instance=driver)

            # Check if the form is valid:
            if form.is_valid():
                # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
                driver = form.save()

                # redirect to a new URL:
                return HttpResponseRedirect(reverse('rideshare:driverMain') )

        # If this is a GET (or any other method) create the default form.       
        return render(request, "rideshare/driver/edit.html", {'form': form})

    @login_required()
    def driverMain(request):
        if Driver.objects.filter(user=request.user).count() == 0:
            return HttpResponseRedirect(reverse('rideshare:driverRegister') )
        driver = get_object_or_404(Driver, user=request.user)
        #driver = Driver.objects.get(user=request.user)
        rides = Ride.objects.filter(driver=driver, status=RideStatus.CONFIRMED.value).order_by('required_arrival_time')
        complete_rides = Ride.objects.filter(driver=driver, status=RideStatus.COMPLETE.value).order_by('id')
        return render(request, "rideshare/driver/main.html", {'rides': rides, 'complete_rides': complete_rides})

    @login_required()
    def driverSearch(request):
        driver = get_object_or_404(Driver, user=request.user)
        if request.method == 'GET':
            if request.GET.get('arrival_time') == "":
                arrival_time = datetime.datetime.now()
            else:
                arrival_time_str = request.GET.get('arrival_time')
                arrival_time = datetime.datetime.strptime(arrival_time_str, "%Y-%m-%d %H:%M")
                
            if request.GET.get('passenger_count') == "":
                passenger_count = driver.capacity
            else:
                passenger_count = int(request.GET.get('passenger_count'))
            destination = request.GET.get('destination', "")

            if passenger_count > driver.capacity:
                passenger_count = driver.capacity
            

            #if passenger_count > driver.capacity:
            #    raise ValidationError("Passenger count exceed your vehicle's capacity.")

            # Perform your search logic based on form input
            results = Ride.objects.filter(
                required_arrival_time__gte=arrival_time,
                vehicle_type=driver.vehicle_type,
                status=RideStatus.OPEN.value,
                special_requests=driver.special_vehicle_info,
                destination_address__contains=destination,
            )
            # .annotate(
            #     total_passengers=Coalesce(Sum('sharer__num_passengers'), Value(0), output_field=IntegerField())
            # ).filter(
            #     total_passengers__lte=F('driver__capacity') - F('num_passengers')
            # )
            print(results)

            return render(request, 'rideshare/driver/search.html', {'results': results})
        return render(request, "rideshare/driver/search.html")

# Owner
from django.views import generic
#class OwnerRideListView(generic.ListView):


class OwnerView(LoginRequiredMixin):
 
    def owner_rides_view(request):
        user = request.user
        owner_rides = user.rides_as_owner.all()
        return render(request, "rideshare/ride_list.html", {'ride_list': owner_rides})


    def owner_request_view(request):
        from .models import Ride  # Import the Ride model if not already imported

    def owner_request_view(request):
        user = request.user
        if request.method == 'POST':
            form = OwnerRequestForm(request.POST)
            if form.is_valid():
                new_ride = Ride(
                    destination_address=form.cleaned_data['destination'],
                    required_arrival_time=form.cleaned_data['required_arrival_time'],
                    vehicle_type=form.cleaned_data['vehicle_type'],
                    num_passengers=form.cleaned_data['num_passengers'],
                    shared=form.cleaned_data['shared'],
                    special_requests=form.cleaned_data['special_requests'],  
                    status=RideStatus.OPEN.value,
                    owner=user, 
                )

docker-deploy/web-app/rideshare/templates/rideshare/driver/edit.html
{% extends "base_generic.html" %}

{% block content %}
<head>
  <meta charset="UTF-8">
  <title> Responsive Registration Form | CodingLab </title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'rideshare/css/register.css' %}" >
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="container" id ="reg-cont">
    <div class="title">Driver Info</div>
    <div class="content">
      <form action="" method="post">
        <div class="user-details">

          {% csrf_token %}
          {% for field in form %}
            <div class="input-box">
              <span class="details"> {{ field.label }} </span>
              {{ field }}
            </div>
          {% endfor %}
        </div>

        <div class="button">
          <input type="submit" value="Update">
        </div>
      </form>
    </div>
  </div>
</body>
{% endblock %}

docker-deploy/web-app/rideshare/templates/rideshare/driver/main.html
{% extends "base_generic.html" %}

{% block content %}
<head>
  <title>{% block title %}{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'rideshare/css/main.css' %}">
  <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
  {% load bootstrap5 %}
  {% bootstrap_css %}
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
  <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
  {% bootstrap_javascript %}
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"></script>
</head>
<body>
<div class="content">
  <div class="container py-3">
    <div class="row">
      <h2 class="font-weight-light mb-4 font-italic text-white">
        <a href="{% url 'rideshare:driverEdit' %}" class="text-white d-flex align-items-center">
          <i class="fa fa-user fa-lg me-2"></i>
          <span>Driver Info</span>
        </a>
      </h2>
      <div class="col-lg-9 mx-auto">
        <h2 class="font-weight-light mb-4 font-italic text-white">Search for Open Rides</h2>
        <div class="bg-white p-5 rounded shadow">
          <form action="{% url 'rideshare:driverSearch' %}" method="get">
            <div class="row">
              <div class="col-lg-12">
                <div class="row">
                  <input type="text" class="form-control search-slt" id="destination" name="destination" placeholder="Enter Destination">
                </div>
                <div class="row d-flex align-items-stretch">
                  <div class="col-lg-6 col-md-6 col-sm-12 p-0 d-flex align-items-stretch">
                    <div class="input-group date" id="datetimePicker" data-target-input="nearest">
                      <input type="text" class="form-control datetimepicker-input" data-target="#datetimePicker" name="arrival_time" placeholder="Earlist Arrival Date and Time" />
                      <div class="input-group-append" data-target="#datetimePicker" data-toggle="datetimepicker">
                          <div class="input-group-text"><i class="fa fa-calendar text-center"></i></div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-5 col-md-5 col-sm-12 p-0">
                    <input type="number" class="form-control search-slt" id="passenger_count" name="passenger_count" min="1"
                     placeholder="Number of Passengers">
                  </div>
                  <div class="col-lg-1 col-md-1 col-sm-12 p-0 bg-secondary text-center">
                    <button id="button-addon1" type="submit" class="btn btn-link text-white"><i class="fa fa-search fa-lg"></i></button>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="text-center mt-3 mb-3 text-white">
      <h3>Confirmed Rides</h3>
    </div>

    {% for ride in rides %}
    <div class="card mb-3">
      <div class="card-body">
        <div class="d-flex flex-column flex-lg-row">
            <span class="avatar avatar-text rounded-3 me-4 mb-2  {% cycle 'avatar-0' 'avatar-1' 'avatar-2' 'avatar-3' 'avatar-4' %}">{{ forloop.counter }}</span>
            <div class="row flex-fill">
              <div class="col-sm-3">
                <h4 class="h5">{{ride.destination_address}}</h4>
                <span class="badge bg-warning">{{ride.required_arrival_time}}</span>
              </div>
              <div class="col-sm-6 py-2">
                <span class="badge owner-badge fs-6">
                  {{ride.owner.first_name}} <br>
                  (passengers: {{ride.num_passengers}})
                </span>
                {% for sharer in ride.sharer_set.all %}
                  <span class="badge sharer-badge fs-6">
                    {{sharer.user.first_name}} <br>
                    (passengers: {{sharer.num_passengers}})
                  </span>
                {% endfor %}
              </div>
              <div class="col-sm-1 text-lg-end py-2">
                <a href="{% url 'rideshare:ride-detail' pk=ride.id %}" class="btn btn-secondary">Info</a>
              </div>
              <div class="col-sm-1 text-lg-end py-2">
                <a href="{% url 'rideshare:updateRideStatus' ride_id=ride.id status='Complete'%}" class="btn btn-secondary">Complete</a>
              </div>
            </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  <div class="container">
    <div class="text-center mt-3 mb-3 text-white">
      <h3>Complete Rides</h3>
    </div>

    {% for ride in complete_rides %}
    <div class="card mb-3">
      <div class="card-body">
        <div class="d-flex flex-column flex-lg-row">
            <span class="avatar avatar-text rounded-3 me-4 mb-2  {% cycle 'avatar-0' 'avatar-1' 'avatar-2' 'avatar-3' 'avatar-4' %}">{{ forloop.counter }}</span>
            <div class="row flex-fill">
              <div class="col-sm-3">
                <h4 class="h5">{{ride.destination_address}}</h4>
                <span class="badge bg-warning">{{ride.required_arrival_time}}</span>
              </div>
              <div class="col-sm-7 py-2">
                <span class="badge owner-badge fs-6">
                  {{ride.owner.first_name}} <br>
                  (passengers: {{ride.num_passengers}})
                </span>
                {% for sharer in ride.sharer_set.all %}
                  <span class="badge sharer-badge fs-6">
                    {{sharer.user.first_name}} <br>
                    (passengers: {{sharer.num_passengers}})
                  </span>
                {% endfor %}
              </div>
              <div class="col-sm-1 text-lg-end py-2">
                <a href="{% url 'rideshare:ride-detail' pk=ride.id %}" class="btn btn-secondary">Info</a>
              </div>
            </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
</body>
<script>
  $(function () {
      $('#datetimePicker').datetimepicker({
          format: 'YYYY-MM-DD HH:mm',  // Customize the datetime format as needed
      });
  });
</script>

{% endblock %}

docker-deploy/web-app/rideshare/templates/rideshare/driver/register.html
{% extends "base_generic.html" %}

{% block content %}
<!-- Created By CodingLab - www.codinglabweb.com -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <title> Responsive Registration Form | CodingLab </title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'rideshare/css/register.css' %}" >
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
<body>
  <div class="container" id="reg-cont">
    <div class="title">Driver Registration</div>
    <div class="content">
      <form action="" method="post">
        <div class="user-details">

          {% csrf_token %}
          {% for field in form %}
            <div class="input-box">
              <span class="details"> {{ field.label }} </span>
              {{ field }}
            </div>
          {% endfor %}
        </div>

        <div class="button">
          <input type="submit" value="Register">
        </div>
      </form>
    </div>
  </div>
</body>
</html>
{% endblock %}

docker-deploy/web-app/rideshare/templates/rideshare/driver/search.html
{% extends "base_generic.html" %}

{% block content %}
<head>
  <title>{% block title %}{% endblock %}</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'rideshare/css/main.css' %}">
  <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
  {% load bootstrap5 %}
  {% bootstrap_css %}
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
  <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
  {% bootstrap_javascript %}
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js"></script>
</head>

<body>
  <div class="content">
  <div class="container py-3">
    <div class="row">
      <h2 class="col-lg-8 font-weight-light mb-4 font-italic text-white d-flex align-items-center">
        <a href="{% url 'rideshare:driverEdit' %}" class="text-white d-flex align-items-center">
          <i class="fa fa-user fa-lg me-2"></i>
          <span>Driver Info</span>
        </a>
      </h2>
      <div class="col-lg-4 text-end align-items-top">
        <a href="{% url 'rideshare:driverMain' %}" class="btn btn-info">Confirmed Rides</a>
      </div>
      <div class="col-lg-9 mx-auto">
        <h2 class="font-weight-light mb-4 font-italic text-white">Search for Open Rides</h2>
        <div class="bg-white p-5 rounded shadow">
          <form action="{% url 'rideshare:driverSearch' %}" method="get">
            <div class="row">
              <div class="col-lg-12">
                <div class="row">
                  <input type="text" class="form-control search-slt" id="destination" name="destination" placeholder="Enter Destination">
                </div>
                <div class="row d-flex align-items-stretch">
                  <div class="col-lg-6 col-md-6 col-sm-12 p-0 d-flex align-items-stretch">
                    <div class="input-group date" id="datetimePicker" data-target-input="nearest">
                      <input type="text" class="form-control datetimepicker-input" data-target="#datetimePicker" name="arrival_time" placeholder="Earliest Arrival Time" />
                      <div class="input-group-append" data-target="#datetimePicker" data-toggle="datetimepicker">
                          <div class="input-group-text"><i class="fa fa-calendar text-center"></i></div>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-5 col-md-5 col-sm-12 p-0">
                    <input type="number" class="form-control search-slt" id="passenger_count" name="passenger_count" min="1"
                     placeholder="Number of Passengers">
                  </div>
                  <div class="col-lg-1 col-md-1 col-sm-12 p-0 bg-secondary text-center">
                    <button id="button-addon1" type="submit" class="btn btn-link text-white "><i class="fa fa-search fa-lg"></i></button>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    {% if results %}
    {% for ride in results %}
    <div class="card mb-3">
      <div class="card-body">
        <div class="d-flex flex-column flex-lg-row">
            <span class="avatar avatar-text rounded-3 me-4 mb-2  {% cycle 'avatar-0' 'avatar-1' 'avatar-2' 'avatar-3' 'avatar-4' %}">{{ forloop.counter }}</span>
            <div class="row flex-fill">
              <div class="col-sm-3">
                <h4 class="h5">{{ride.destination_address}}</h4>
                <span class="badge bg-warning">{{ride.required_arrival_time}}</span>
              </div>
              <div class="col-sm-6 py-2">
                <span class="badge owner-badge fs-6">
                  {{ride.owner.first_name}} <br>
                  (passengers: {{ride.num_passengers}})
                </span>
                {% for sharer in ride.sharer_set.all %}
                  <span class="badge sharer-badge fs-6">
                    {{sharer.user.first_name}} <br>
                    (passengers: {{sharer.num_passengers}})
                  </span>
                {% endfor %}
              </div>
              <div class="col-sm-1 text-lg-end py-2">
                <a href="{% url 'rideshare:ride-detail' pk=ride.id %}" class="btn btn-secondary">Info</a>
              </div>
              <div class="col-sm-1 text-lg-end py-2">
                <a href="{% url 'rideshare:updateRideStatus' ride_id=ride.id status='Confirmed' %}" class="btn btn-secondary">Confirm</a>
              </div>
            </div>
        </div>
      </div>
    </div>
    {% endfor %}
    {% else %}
      <div class="text-center">
        <p>No results found.</p>
      </div>
    {% endif %}
  </div>
</div>
</body>

<script>
  $(function () {
      $('#datetimePicker').datetimepicker({
          format: 'YYYY-MM-DD HH:mm',  // Customize the datetime format as needed
      });
  });
</script>

{% endblock %}